kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
  
---

kind: pipeline
name: python-flask-test

steps:
- name: test
  image: python:2
  commands:
  - pip install pipenv
  - pipenv install -r requirements.txt
